name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
        chmod 600 ~/.ssh/deploy-key.pem
        cat >> ~/.ssh/config << EOF
        Host my-vps
          HostName ${{ secrets.SSH_IP }}
          User ${{ secrets.SSH_USER }}
          IdentityFile ~/.ssh/deploy-key.pem
          StrictHostKeyChecking no
        EOF

    - name: Deploy site
      run: |
        ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && git pull origin main && docker compose -f docker-compose.prod.yml down && docker compose -f docker-compose.prod.yml up -d --build" 